### ISSUE TITLE
MetaPhlAn3 column inconsistencies

### ISSUE THREAD

**Issue by cmirzayi** [waldronlab/curatedMetagenomicData#168] opened 2021-03-02 16:16 UTC
Processing datasets through the `make_data()` step of the cMD pipeline currently results in warning messages that look like this:

```
Warning: 22 parsing failures.
row col  expected    actual                                                        file
 52  -- 4 columns 3 columns './tmp/AsnicarF_2017/metaphlan_bugs_list/MV_FEI1_t1Q14.tsv'
 53  -- 4 columns 3 columns './tmp/AsnicarF_2017/metaphlan_bugs_list/MV_FEI1_t1Q14.tsv'
 54  -- 4 columns 3 columns './tmp/AsnicarF_2017/metaphlan_bugs_list/MV_FEI1_t1Q14.tsv'
 55  -- 4 columns 3 columns './tmp/AsnicarF_2017/metaphlan_bugs_list/MV_FEI1_t1Q14.tsv'
 57  -- 4 columns 3 columns './tmp/AsnicarF_2017/metaphlan_bugs_list/MV_FEI1_t1Q14.tsv'
... ... ......... ......... ...........................................................
```

The `make_data()` function should be updated to accept the new 4th column in MetaPhlAn3 profiles.

**Comment by lwaldron** [comment] 2021-03-12 13:07
I think this is a duplicate of https://github.com/waldronlab/curatedMetagenomicData/issues/169

**Comment by lwaldron** [comment] 2021-03-12 13:07
I think this is a duplicate of https://github.com/waldronlab/curatedMetagenomicData/issues/169

**Closed by lwaldron** 2021-03-12 13:07 UTC
