### ISSUE TITLE
cannot coerce class ‘structure("dgTMatrix", package = "Matrix")’ to a data.frame

### ISSUE THREAD

**Issue by zhuzn** [waldronlab/curatedMetagenomicData#253] opened 2021-08-04 01:30 UTC
**Describe the bug**
sampleMetadata %>%
    dplyr::filter(country=="CHN") %>%
    returnSamples("gene_families")

**To Reproduce**
cannot coerce class ‘structure("dgTMatrix", package = "Matrix")’ to a data.frame

**Comment by schifferl** [comment] 2021-08-05 15:43
Hi @zhuzn, I've just investigated this myself and have confirmed this is a bug; thank you for reporting it. I'll work on a patch and send you an update when it's done.

**Comment by szimmerman92** [comment] 2021-08-28 21:05
Hi @zhuzn and @schifferl I found the bug and may have a fix. The error is in the mergeData function which is used in inside returnSamples to merge matrices from multiple studies together. The specific line of code that gives rise to the error is 

`    assays <- purrr::map(mergeList, SummarizedExperiment::assay) %>% 
        purrr::map(base::as.data.frame) %>% purrr::map(tibble::rownames_to_column) %>% 
        purrr::reduce(dplyr::full_join, by = "rowname") %>% tibble::column_to_rownames() %>% 
        dplyr::mutate(dplyr::across(.fns = ~tidyr::replace_na(.x, 
            0))) %>% base::as.matrix() %>% S4Vectors::SimpleList() %>% magrittr::set_names(assay_name)
` 
The specific part that throws the error is `purrr::map(base::as.data.frame)` because as the error advertises you cannot convert a dgTMatrix to a data.frame. You have to first convert it to a matrix, and then convert the matrix to a data frame. However, if you want to then merge multiple dataframes together, this become computationally very difficult. So I found a function native to the R package Seurat, that directly merges sparse matrices together. The edited mergeData function is below.

 `mergeData = function (mergeList) 
{
    if (base::length(mergeList) == 1) {
        stop("mergeList contains only a single element", call. = FALSE)
    }
    assay_name <- purrr::map_chr(mergeList, SummarizedExperiment::assayNames) %>% 
        base::unique()
    if (base::length(assay_name) != 1) {
        stop("dataType of list elements is different", call. = FALSE)
    }
    duplicate_colnames <- purrr::map(mergeList, base::colnames) %>% 
        purrr::reduce(base::intersect)
    if (base::length(duplicate_colnames) != 0) {
        stop("colnames/sample_id values are not unique", call. = FALSE)
    }
    asssays_list = purrr::map(mergeList, SummarizedExperiment::assay)
    assays = RowMergeSparseMatrices(asssays_list[[1]],asssays_list[-1])
    rowData <- purrr::map(mergeList, SummarizedExperiment::rowData) %>% 
        purrr::map(base::as.data.frame) %>% purrr::map(tibble::rownames_to_column)
    join_by <- purrr::map(rowData, base::colnames) %>% purrr::reduce(base::intersect)
    rowData <- purrr::reduce(rowData, dplyr::full_join, by = join_by) %>% 
        tibble::column_to_rownames() %>% S4Vectors::DataFrame()
    colData <- purrr::map(mergeList, SummarizedExperiment::colData) %>% 
        purrr::map(base::as.data.frame) %>% purrr::map(tibble::rownames_to_column) %>% 
        dplyr::bind_rows() %>% tibble::column_to_rownames() %>% 
        S4Vectors::DataFrame()
    if (assay_name == "relative_abundance") {
        TreeSummarizedExperiment::TreeSummarizedExperiment(assays = assays, 
            rowData = rowData, colData = colData, rowTree = phylogeneticTree)
    }
    else {
        SummarizedExperiment::SummarizedExperiment(assays = assays, 
            rowData = rowData, colData = colData)
    }
}
`

To summarize, I replaced 

`    assays <- purrr::map(mergeList, SummarizedExperiment::assay) %>% 
        purrr::map(base::as.data.frame) %>% purrr::map(tibble::rownames_to_column) %>% 
        purrr::reduce(dplyr::full_join, by = "rowname") %>% tibble::column_to_rownames() %>% 
        dplyr::mutate(dplyr::across(.fns = ~tidyr::replace_na(.x, 
            0))) %>% base::as.matrix() %>% S4Vectors::SimpleList() %>% magrittr::set_names(assay_name)
` 
with 

`    asssays_list = purrr::map(mergeList, SummarizedExperiment::assay)
    assays = RowMergeSparseMatrices(asssays_list[[1]],asssays_list[-1])
`

I am not sure if this is ideal because running this function on around 800 samples still makes my computer run out of memory and for some reason I cannot get ExperimentHub to use a recent snapshot on the computing cluster I normally use, so I can't use the most recent version of curatedMetagenomicData on it.

Hope this helps though!

Best,
Sam

**Closed** 2021-09-28 03:07 UTC
Labels: Bug Report
